---
title: "sisbidDay2_code"
author: "Angie Boysen"
date: "July 12, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

Installing google sheets
```{r install}
# install.packages('googlesheets')
#library(devtools)
#install_github("jennybc/googlesheets")
library(googlesheets)
```

Reading a google sheet
```{r firstread}
sheets_url = "https://docs.google.com/spreadsheets/d/18KQQd4LY5k8Ucux1MvWCsQGQJlvd0ECTnn-3ixdOKFM/pubhtml"

gsurl1 = gs_url(sheets_url)
dat = gs_read(gsurl1)
date_accessed = date()

```

Doing the lab
```{r gslabImport}
sheets_url <- "https://docs.google.com/spreadsheets/d/103vUoftv2dLNZ_FcAz08b5ptIkWN4W2RaFn7VF39FJ8/pubhtml"
gsurl1 = gs_url(sheets_url)
dat = gs_read(gsurl1)

#read just the forst two rows
dat2cols <- gs_read(gsurl1, range = cell_cols(1:2))
```

How many students have entered data? 
``` {r gslabstudentCount}
dat2cols <- dat2cols[!is.na(dat2cols$UW),]
nStudents <- nrow(dat2cols)
nStudents
```

Do students have more than 2 years of experience with R?
```{r yearsofR}
#This way of doing it introduces NAs b/c some folks didn't enter just a number
dat$twoyears <- as.numeric(dat$`Years of R experience`)>2
# create factor "skilled" and "learning"
factorYears <- 2
```


## doing JSON stuff now
load lib/install stuff
```{r installJSON}
# install.packages("jsonlite")
library(jsonlite)
jsonData <- fromJSON(github_url)
dim(jsonData)

```


